name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              timeout-minutes: 2

            - name: Install yarn
              run: npm install -g yarn
              timeout-minutes: 2

            - name: Install dependencies
              run: yarn
              timeout-minutes: 10

            - name: Lint
              run: yarn lint
              timeout-minutes: 5

            - name: Build
              run: yarn build
              timeout-minutes: 10
